<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Pokemon;
use App\Enum\PokemonGame;
use App\ValueObject\Id\PokemonId;

final class PokemonInMemoryRepository implements PokemonRepository
{
    public function findAll(): array
    {
        static $pokemons;

        if (! $pokemons) {
            $pokemons = [
                Pokemon::create(PokemonId::fromInt(1), 'Bulbizarre', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(2), 'Herbizarre', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(3), 'Florizarre', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(4), 'Salamèche', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(5), 'Reptincel', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(6), 'Dracaufeu', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(7), 'Carapuce', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(8), 'Carabaffe', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(9), 'Tortank', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(10), 'Chenipan', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(11), 'Chrysacier', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(12), 'Papilusion', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(13), 'Aspicot', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(14), 'Coconfort', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(15), 'Dardargnan', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(16), 'Roucool', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(17), 'Roucoups', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(18), 'Roucarnage', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(19), 'Rattata', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(20), 'Rattatac', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(21), 'Piafabec', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(22), 'Rapasdepic', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(23), 'Abo', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(24), 'Arbok', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(25), 'Pikachu', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(26), 'Raichu', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(27), 'Sabelette', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(28), 'Sablaireau', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(29), 'Nidoran♀', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(30), 'Nidorina', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(31), 'Nidoqueen', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(32), 'Nidoran♂', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(33), 'Nidorino', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(34), 'Nidoking', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(35), 'Mélofée', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(36), 'Mélodelfe', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(37), 'Goupix', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(38), 'Feunard', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(39), 'Rondoudou', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(40), 'Grodoudou', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(41), 'Nosferapti', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(42), 'Nosferalto', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(43), 'Mystherbe', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(44), 'Ortide', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(45), 'Rafflesia', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(46), 'Paras', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(47), 'Parasect', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(48), 'Mimitoss', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(49), 'Aéromite', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(50), 'Taupiqueur', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(51), 'Triopikeur', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(52), 'Miaouss', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(53), 'Persian', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(54), 'Psykokwak', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(55), 'Akwakwak', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(56), 'Férosinge', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(57), 'Colossinge', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(58), 'Caninos', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(59), 'Arcanin', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(60), 'Ptitard', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(61), 'Têtarte', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(62), 'Tartard', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(63), 'Abra', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(64), 'Kadabra', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(65), 'Alakazam', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(66), 'Machoc', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(67), 'Machopeur', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(68), 'Mackogneur', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(69), 'Chétiflor', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(70), 'Boustiflor', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(71), 'Empiflor', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(72), 'Tentacool', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(73), 'Tentacruel', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(74), 'Racaillou', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(75), 'Gravalanch', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(76), 'Grolem', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(77), 'Ponyta', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(78), 'Galopa', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(79), 'Ramoloss', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(80), 'Flagadoss', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(81), 'Magnéti', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(82), 'Magnéton', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(83), 'Canarticho', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(84), 'Doduo', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(85), 'Dodrio', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(86), 'Otaria', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(87), 'Lamantine', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(88), 'Tadmorv', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(89), 'Grotadmorv', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(90), 'Kokiyas', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(91), 'Crustabri', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(92), 'Fantominus', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(93), 'Spectrum', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(94), 'Ectoplasma', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(95), 'Onix', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(96), 'Soporifik', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(97), 'Hypnomade', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(98), 'Krabby', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(99), 'Krabboss', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(100), 'Voltorbe', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(101), 'Électrode', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(102), 'Noeunoeuf', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(103), 'Noadkoko', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(104), 'Osselait', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(105), 'Ossatueur', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(106), 'Kicklee', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(107), 'Tygnon', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(108), 'Excelangue', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(109), 'Smogo', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(110), 'Smogogo', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(111), 'Rhinocorne', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(112), 'Rhinoféros', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(113), 'Leveinard', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(114), 'Saquedeneu', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(115), 'Kangourex', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(116), 'Hypotrempe', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(117), 'Hypocéan', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(118), 'Poissirène', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(119), 'Poissoroy', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(120), 'Stari', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(121), 'Staross', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(122), 'M. Mime', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(123), 'Insécateur', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(124), 'Lippoutou', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(125), 'Élektek', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(126), 'Magmar', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(127), 'Scarabrute', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(128), 'Tauros', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(129), 'Magicarpe', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(130), 'Léviator', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(131), 'Lokhlass', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(132), 'Métamorph', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(133), 'Évoli', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(134), 'Aquali', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(135), 'Voltali', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(136), 'Pyroli', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(137), 'Porygon', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(138), 'Amonita', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(139), 'Amonistar', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(140), 'Kabuto', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(141), 'Kabutops', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(142), 'Ptéra', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(143), 'Ronflex', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(144), 'Artikodin', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(145), 'Électhor', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(146), 'Sulfura', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(147), 'Minidraco', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(148), 'Draco', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(149), 'Dracolosse', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(150), 'Mewtwo', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(151), 'Mew', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(152), 'Germignon', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(153), 'Macronium', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(154), 'Méganium', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(155), 'Héricendre', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(156), 'Feurisson', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(157), 'Typhlosion', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(158), 'Kaiminus', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(159), 'Crocrodil', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(160), 'Aligatueur', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(161), 'Fouinette', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(162), 'Fouinar', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(163), 'Hoothoot', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(164), 'Noarfang', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(165), 'Coxy', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(166), 'Coxyclaque', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(167), 'Mimigal', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(168), 'Migalos', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(169), 'Nostenfer', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(170), 'Loupio', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(171), 'Lanturn', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(172), 'Pichu', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(173), 'Mélo', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(174), 'Toudoudou', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(175), 'Togepi', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(176), 'Togetic', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(177), 'Natu', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(178), 'Xatu', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(179), 'Wattouat', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(180), 'Lainergie', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(181), 'Pharamp', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(182), 'Joliflor', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(183), 'Marill', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(184), 'Azumarill', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(185), 'Simularbre', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(186), 'Tarpaud', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(187), 'Granivol', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(188), 'Floravol', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(189), 'Cotovol', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(190), 'Capumain', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(191), 'Tournegrin', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(192), 'Héliatronc', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(193), 'Yanma', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(194), 'Axoloto', [PokemonGame::RedFire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(195), 'Maraiste', [PokemonGame::RedFire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(196), 'Mentali', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(197), 'Noctali', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(198), 'Cornèbre', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(199), 'Roigada', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(200), 'Feuforêve', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(201), 'Zarbi', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(202), 'Qulbutoké', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(203), 'Girafarig', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(204), 'Pomdepik', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(205), 'Foretress', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(206), 'Insolourdo', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(207), 'Scorplane', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(208), 'Steelix', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(209), 'Snubbull', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(210), 'Granbull', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(211), 'Qwilfish', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(212), 'Cizayox', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(213), 'Caratroc', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(214), 'Scarhino', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(215), 'Farfuret', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(216), 'Teddiursa', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(217), 'Ursaring', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(218), 'Limagma', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(219), 'Volcaropod', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(220), 'Marcacrin', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(221), 'Cochignon', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(222), 'Corayon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(223), 'Rémoraid', [PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(224), 'Octillery', [PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(225), 'Cadoizo', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(226), 'Démanta', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(227), 'Airmure', [PokemonGame::RedFire, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(228), 'Malosse', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(229), 'Démolosse', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(230), 'Hyporoi', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(231), 'Phanpy', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(232), 'Donphan', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(233), 'Porygon2', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(234), 'Cerfrousse', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(235), 'Queulorior', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(236), 'Debugant', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(237), 'Kapoera', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(238), 'Lippouti', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(239), 'Élekid', [PokemonGame::RedFire]),
                Pokemon::create(PokemonId::fromInt(240), 'Magby', [PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(241), 'Écrémeuh', [PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(242), 'Leuphorie', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(243), 'Raikou', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(244), 'Entei', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(245), 'Suicune', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(246), 'Embrylex', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(247), 'Ymphect', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(248), 'Tyranocif', [PokemonGame::RedFire, PokemonGame::GreenLeaf]),
                Pokemon::create(PokemonId::fromInt(249), 'Lugia', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(250), 'Ho-Oh', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(251), 'Celebi', []),
                Pokemon::create(PokemonId::fromInt(252), 'Arcko', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(253), 'Massko', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(254), 'Jungko', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(255), 'Poussifeu', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(256), 'Galifeu', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(257), 'Braségali', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(258), 'Gobou', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(259), 'Flobio', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(260), 'Laggron', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(261), 'Medhyèna', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(262), 'Grahyèna', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(263), 'Zigzaton', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(264), 'Linéon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(265), 'Chenipotte', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(266), 'Armulys', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(267), 'Charmillon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(268), 'Blindalys', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(269), 'Papinox', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(270), 'Nénupiot', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(271), 'Lombre', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(272), 'Ludicolo', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(273), 'Grainipiot', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(274), 'Pifeuil', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(275), 'Tengalice', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(276), 'Nirondelle', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(277), 'Hélédelle', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(278), 'Goélise', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(279), 'Bekipan', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(280), 'Tarsal', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(281), 'Kirlia', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(282), 'Gardevoir', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(283), 'Arakdo', [PokemonGame::Ruby, PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(284), 'Maskadra', [PokemonGame::Ruby, PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(285), 'Balignon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(286), 'Chapignon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(287), 'Parecool', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(288), 'Vigoroth', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(289), 'Monaflèmit', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(290), 'Ningale', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(291), 'Ninjask', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(292), 'Munja', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(293), 'Chuchmur', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(294), 'Ramboum', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(295), 'Brouhabam', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(296), 'Makuhita', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(297), 'Hariyama', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(298), 'Azurill', [PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(299), 'Tarinor', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(300), 'Skitty', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(301), 'Delcatty', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(302), 'Ténéfix', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(303), 'Mysdibule', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(304), 'Galekid', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(305), 'Galegon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(306), 'Galeking', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(307), 'Méditikka', [PokemonGame::Ruby, PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(308), 'Charmina', [PokemonGame::Ruby, PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(309), 'Dynavolt', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(310), 'Élecsprint', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(311), 'Posipi', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(312), 'Négapi', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(313), 'Muciole', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(314), 'Lumivole', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(315), 'Rosélia', [PokemonGame::Ruby, PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(316), 'Gloupti', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(317), 'Avaltout', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(318), 'Carvanha', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(319), 'Sharpedo', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(320), 'Wailmer', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(321), 'Wailord', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(322), 'Chamallot', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(323), 'Camérupt', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(324), 'Chartor', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(325), 'Spoink', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(326), 'Groret', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(327), 'Spinda', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(328), 'Kraknoix', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(329), 'Vibraninf', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(330), 'Libégon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(331), 'Cacnea', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(332), 'Cacturne', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(333), 'Tylton', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(334), 'Altaria', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(335), 'Mangriff', [PokemonGame::Ruby]),
                Pokemon::create(PokemonId::fromInt(336), 'Séviper', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(337), 'Séléroc', [PokemonGame::Sapphire]),
                Pokemon::create(PokemonId::fromInt(338), 'Solaroc', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(339), 'Barloche', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(340), 'Barbicha', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(341), 'Écrapince', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(342), 'Colhomard', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(343), 'Balbuto', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(344), 'Kaorine', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(345), 'Lilia', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(346), 'Vacilys', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(347), 'Anorith', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(348), 'Armaldo', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(349), 'Barpau', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(350), 'Milobellus', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(351), 'Morphéo', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(352), 'Kecleon', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(353), 'Polichombr', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(354), 'Branette', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(355), 'Skelénox', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(356), 'Téraclope', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(357), 'Tropius', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(358), 'Éoko', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(359), 'Absol', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(360), 'Okéoké', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(361), 'Stalgamin', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(362), 'Oniglali', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(363), 'Obalie', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(364), 'Phogleur', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(365), 'Kaimorse', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(366), 'Coquiperl', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(367), 'Serpang', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(368), 'Rosabyss', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(369), 'Relicanth', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(370), 'Lovdisc', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(371), 'Draby', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(372), 'Drackhaus', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(373), 'Drattak', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(374), 'Terhal', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(375), 'Métang', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(376), 'Métalosse', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(377), 'Regirock', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(378), 'Regice', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(379), 'Registeel', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(380), 'Latias', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(381), 'Latios', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(382), 'Kyogre', [PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(383), 'Groudon', [PokemonGame::Ruby, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(384), 'Rayquaza', [PokemonGame::Ruby, PokemonGame::Sapphire, PokemonGame::Emerald]),
                Pokemon::create(PokemonId::fromInt(385), 'Jirachi', []),
                Pokemon::create(PokemonId::fromInt(386), 'Deoxys', [PokemonGame::RedFire, PokemonGame::GreenLeaf, PokemonGame::Emerald]),
            ];
        }

        return $pokemons;
    }
}
